# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "/:title/"

# Setup
title:               Cesar Renteria
tagline:             Ph.D. Student
description:         'Ph.D. Student in Public Administration & Policy'
url:                 "https://crenteriam.github.io"         
paginate:            5

# About/contact
author:
  name:              Cesar Renteria Marin
  url:               https://twitter.com/crenteriama
  email:             crenteria@albany.edu

# Custom vars
version:             1.0
github:

# ---------------------------------------------------------------
# Font Settings
# - Find fonts on Google Fonts (https://www.google.com/fonts)
# - All fonts set here will have the following styles:
#     light, light italic, normal, normal italic, bold, bold italic
# - Be aware that setting too much fonts will cause site running slowly
# - Introduce in 5.0.1
# ---------------------------------------------------------------
font:
  enable: true

  # URL of fonts host. E.g. //fonts.googleapis.com (Default)
  host: //fonts.googleapis.com

  # Global font settings used on <body> element.
  global:
    # external: true will load this font family from host.
    external: true
    family: Helvetica

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6)
  # Fallback to `global` font settings.
  headings:
    external: true
    family: Roboto Slab

  # Font settings for posts
  # Fallback to `global` font settings.
  #posts:
    #external: true
    #family:

  # Font settings for Logo
  # Fallback to `global` font settings.
  # The `size` option use `px` as unit
  #logo:
    #external: true
    #family:
    #size:

  # Font settings for <code> and code blocks.
  #codes:
    #external: true
    #family:
    #size:
    
    # Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
