# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "/:title/"

# Setup
title:               Cesar Renteria
tagline:             Ph.D. Student
description:         'Ph.D. Student in Public Administration & Policy'
url:                 "https://crenteriam.github.io"         
paginate:            5

# About/contact
author:
  name:              Cesar Renteria Marin
  url:               https://twitter.com/crenteriama
  email:             crenteria@albany.edu

# Custom vars
version:             1.0
github:

# Font Type
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Coiny"
    weights: "400,400i,700,700i"
